# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:55
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="reporter_email",
            field=models.CharField(blank=True, max_length=1000),
        )
    ]
