# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0002_conversation_reporter_email")]

    operations = [migrations.RemoveField(model_name="message", name="stripped_signature")]
