# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_message_quoted_text"),
        ("main", "0004_conversation_sender_email"),
    ]

    operations: list = []
