# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_merge_20161003_1219")]

    operations = [
        migrations.CreateModel(
            name="ReplyTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=main.models.generate_uuid,
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
            ],
            options={"abstract": False},
        )
    ]
