# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:46
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import main.models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_replytemplate")]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="secret_key",
            field=models.CharField(default=main.models.generate_key, max_length=1000),
        )
    ]
