# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:04
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import main.models


def add_category(apps, schema_editor):
    SpamCategory = apps.get_model("main", "SpamCategory")
    SpamCategory.objects.create(name="Other", default=True)


class Migration(migrations.Migration):

    dependencies = [("main", "0007_conversation_secret_key")]

    operations = [
        migrations.CreateModel(
            name="SpamCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=main.models.generate_uuid,
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("default", models.BooleanField(default=False, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.RunPython(add_category),
    ]
