# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161025_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spamcategory',
            options={'verbose_name_plural': 'spam categories'},
        ),
        migrations.AlterField(
            model_name='spamcategory',
            name='default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
