# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_auto_20161025_1320")]

    operations = [
        migrations.AddField(model_name="conversation", name="classified", field=models.BooleanField(default=False))
    ]
