# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0011_conversation_classified")]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="classified",
            field=models.BooleanField(db_index=True, default=False),
        )
    ]
