# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0012_auto_20161120_0050")]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="reporter_email",
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        )
    ]
